import type { Metadata } from "next";

import "./globals.css";
import Footer from "@/components/Footer";

import NavbarServer from "@/components/NavbarServer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="cupcake">
      <body>
        <NavbarServer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
